[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Omit from coverage
[coverage:run]
omit =
    .venv/*
    tests/*
    __pycache__/*
    build.py
    build_config.py

[coverage:report]
exclude_lines =
    pragma: no cover
    if __name__ == .__main__.:
    pass
